# Change these first
owner: CS-METIS
repo: p1-status-page

sites:
  - name: AI4GEO main site
    url: https://ai4geo.csgroup.eu/
  - name: P1 Landing page
    url: https://p1.csgroup.space
  - name: Data analytics
    url: https://superset.p1.csgroup.space
  - name: Feature server
    url: https://feature.p1.csgroup.space/
   
assignees: # Users to assign downtime issues (optional)
  - geonux
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.p1.csgroup.space
  # baseUrl: /p1-status-page
  logoUrl: https://p1.csgroup.space/static/images/ai4geo-couleur-logo.png
  name: P1 Services status
  introTitle: "This is the uptime monitor and status page for the **METIS P1 Platform**."
  introMessage: If a service doesn't work properly, you may find the reason here. If not, please open an issue.
  navbar:
    - title: Status
      href: /
    - title: Return to platform
      href: https://p1.csgroup.space
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
