# Change these first
owner: CS-METIS
repo: p1-status-page

sites:
  - name: AI4GEO main site
    url: https://ai4geo.csgroup.eu/
  - name: P1
    url: https://p1.csgroup.space
  - name: Data Analytics
    url: https://superset.p1.csgroup.space
  - name: PGAdmin
    url: https://pgadmin.p1.csgroup.space
  - name: PGAdmin
    url: https://pgadmin.p1.csgroup.space
   
assignees: # Users to assign downtime issues (optional)
  - geonux
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /p1-status-page
  logoUrl: https://p1.csgroup.space/static/images/ai4geo-couleur-logo.png
  name: P1 Services status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Goto site
      href: https://p1.csgroup.space
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
